### ISSUE TITLE
Timer or limited uses.

### ISSUE THREAD

**Issue by meadah** [eternalphoenix64/Survival#11]
the other fish and hunt aliases have a way to limit how often or how many uses an alias has per day. I am windering if this is possible with these? 

I have seen aliases that keep track # of uses like hunt. (at the bottom it would display "you have hunted 1/6 times today 5 uses left" or on the fishing it would not allow you to use it for a set amount of time (was in seconds) and we would display something like "The fish are scattered do to your last attempt, you may try again in 'x' minutes." I have a westmarch style server but wNt to prevent players spamming these as they take time and they want to abuse it to make some Easy gold.

**Comment by eternalphoenix64** [comment]
In `!survival settings`, it displays an embed with instructions for changing your `SurvSettings` svar, one of those settings is a cooldown. At this time, you can only implement a global cooldown or a per-alias cooldown. In my next update of the collection, I'll be implementing a hybrid cooldown option, which will further help reduce spamming. I've been a bit buried in work IRL lately and haven't had the energy to devote to aliasing recently.

The default SurvSettings data is shown below. If you want a global cooldown, you need to change the `false` after "cooldown" to `true`, and change the `0` after "coolTime" to the number of seconds you want the cooldown to be. For example, if you want a 1 hour cooldown, you would change it to `3600`. If you want the individual aliases to have individual cooldowns, you have to change each `"xxxxCool"` from `false` to `true`, and give them a time (for example, you can have fishing be 1 hour, hunting be 2 hours, and foraging be 1.5 hours)
```
{"fishFind": [10,50,80,95], "fishHarvDC": 20, "huntFind": [10,45,75,90], "huntHarvDC": 22, "foraFind": [15,40,85,90], "foraHarvDC": 17, "harvest": true, "cooldown": false, "coolTime": 0, "fishCool": false, "fishCoolTime": 0, "huntCool": false, "huntCoolTime": 0, "forageCool": false, "forageCoolTime": 0}
```

If you have any further questions, please reach out to me on Discord, it would make helping you easier.
