### ISSUE TITLE
Hunt Aquatic small / large

### ISSUE THREAD

**Issue by Ssisal** [eternalphoenix64/Survival#5]
No problem.

Just wondering if you could add a hunt aquatic fresh for swamp/lake creatures and a hunt aquatic ocean for salt water creatures for those of us with water breathing that dont need to reside upon the surface. 

In honesty am also interested in something that would take a sailing ship, warship or fleet of them and allow for whaling or colossal sea creature hunting.

**Comment by eternalphoenix64** [comment]
Will be added in next update, targeting end of the week

**Comment by eternalphoenix64** [comment]
Completed and live
