### ISSUE TITLE
Hunt bug

### ISSUE THREAD

**Issue by trinityamad** [eternalphoenix64/Survival#6]
**Describe the bug**
I'm here to report a problem with your "survival" alias.
While the fish and forage commands work flawlessly, the same cannot be said for the hunt command.
Avrae returns in dm this error report: 
```
Error on line 199, col 18:
        huntlist.append(int(i.raw.automation[0].effects[0].attackBonus))
                  ^
ValueError: invalid literal for int() with base 10: 'dexterityMod+proficiencyBonus+3'
```
While on chat appears:
`Error evaluating expression: invalid literal for int() with base 10: 'strengthMod+proficiencyBonus+2'`

**To Reproduce**
Just wrote `!hunt big deer` on discord chat, it doesn't work even with the argument "small" o "large".

**Comment by eternalphoenix64** [comment]
Resolved. Patched
